<?php

namespace App\Http\Requests\Source;

use Illuminate\Foundation\Http\FormRequest;

class EditRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(): array
    {
        return [
            'name'=>['required', 'string', 'min:3', 'max:30'],
            'url' =>['required', 'string'],
            'description' =>['required', 'string']
        ];
    }

    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes(): array
    {
        return [
            'name'=>'"Название источника"',
            'url' =>'"URL источника"',
            'description' =>'"Описание источника"'
        ];
    }

}
